# Use an official Python image
FROM python:alpine

# Set working directory inside container
WORKDIR /app

# Copy files into container
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port
EXPOSE 8002

# Run the app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
